In [1]:
#!pip install pandas

In [2]:
import pandas as pd

music_df = pd.read_csv("Music Info.csv")
listen_df = pd.read_csv("User Listening History.csv")

In [3]:
top_users = (
    listen_df["user_id"]     # select the top 1000 most active users based on number of listening records
    .value_counts()
    .head(1000)
    .index
)

filtered_df = listen_df[
    listen_df["user_id"].isin(top_users) # keep only listening records belonging to the selected top 1000 users
]

In [4]:
filtered_df.shape # show the size of the filtered dataset

(180628, 3)

In [5]:
filtered_df["user_id"].nunique() # verify that the filtered dataset contains 1000 unique users

1000

In [6]:
merged_df = pd.merge(    # merge listening history with music information using track_id
    filtered_df,
    music_df,
    on="track_id",
    how="inner"
)

In [7]:
merged_df.shape # check the size of the merged dataset

(180628, 23)

In [8]:
user_item_matrix = merged_df.pivot_table(
    index="user_id",
    columns="track_id",
    values="playcount",
    fill_value=0
)

user_item_matrix.shape

(1000, 17358)

In [9]:
user_item_matrix.head()

track_id,TRAAAED128E0783FAB,TRAABJS128F9325C99,TRAACKM12903CE5BE9,TRAACPH12903CF5F14,TRAACZN128F93236B1,TRAACZR12903CDD291,TRAADCQ128F932EC14,TRAADNN128F42B1D94,TRAADQW128F427CE68,TRAADQX128F422B4CF,...,TRZZSQU128F92FCDE8,TRZZUBQ128F9351D51,TRZZUTD12903CADD68,TRZZXJT128F931D72C,TRZZXOQ128F932A083,TRZZXVN128F93285B4,TRZZYMU128E0792400,TRZZZCN128F9317A03,TRZZZHL128F9329CFB,TRZZZRJ128F42819AF
user_id,,,,,,,,,,,,,,,,,,,,,
001889ee41b5f31c404a1abe4af07b2377fa776b,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
002b63a7e2247de6d62bc62f253474edc7dd044c,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0037cbbc2cd55e2ba6d6839b15175522339aadec,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
005a475315cd3a29638cf242c4b7c71194e81642,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00a55d1ba6f63109c208dbd80570520d5d80f563,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(user_item_matrix)

similarity_df = pd.DataFrame(
    similarity,
    index=user_item_matrix.index,
    columns=user_item_matrix.index
)

In [11]:
similarity_df.head()

user_id,001889ee41b5f31c404a1abe4af07b2377fa776b,002b63a7e2247de6d62bc62f253474edc7dd044c,0037cbbc2cd55e2ba6d6839b15175522339aadec,005a475315cd3a29638cf242c4b7c71194e81642,00a55d1ba6f63109c208dbd80570520d5d80f563,00b9144fc8cd453b81c362b30dbf8b8266eec220,00c5d0454084e350fce790e87b4db8f2a9925d6d,00d7dede8a10a03ea0b2d4a08449a9776d414923,012c1e24e2b24416a3a50a88ad749259666e946a,0167130264b1fb95133ff4b9453338c6f640fa65,...,fde84664f22fc6527d9285fe9fb0115e32098cb1,fdfba8f727a768304249fbc7d6bb27d44f2dc569,fe04b6b9b34954b5df920f800c0135411fe03db9,fe7a269ac6c58cf78d2a0049aed33f9301416979,fe9a05c03c29da973743a83b80d1660748077432,feee315cf240084e21428c7ddc41bed4c10b3c26,fef771ab021c200187a419f5e55311390f850a50,ff0dd3c172a6e27af78bc2a0a64509578496fcf4,ff2a500e97ee2a48af641cbadcca17a4d54a4e87,ff75f58dff87e9f9f767134882e515e75cd94dde
user_id,,,,,,,,,,,,,,,,,,,,,
001889ee41b5f31c404a1abe4af07b2377fa776b,1.000000,0.105672,0.018497,0.008450,0.000000,0.022293,0.000000,0.023710,0.012256,0.005248,...,0.004457,0.009222,0.000806,0.000000,0.001468,0.012651,0.030636,0.000000,0.009735,0.002338
002b63a7e2247de6d62bc62f253474edc7dd044c,0.105672,1.000000,0.030416,0.067989,0.000811,0.039992,0.000000,0.049071,0.056861,0.000000,...,0.001374,0.062554,0.002650,0.090315,0.004826,0.006068,0.032185,0.001948,0.020510,0.001441
0037cbbc2cd55e2ba6d6839b15175522339aadec,0.018497,0.030416,1.000000,0.021318,0.019554,0.103605,0.000000,0.072191,0.050447,0.034142,...,0.000000,0.023572,0.115318,0.017827,0.032737,0.054875,0.037175,0.004403,0.050895,0.024986
005a475315cd3a29638cf242c4b7c71194e81642,0.008450,0.067989,0.021318,1.000000,0.002393,0.053847,0.000000,0.049396,0.073919,0.010186,...,0.016220,0.013426,0.015834,0.007615,0.001068,0.052186,0.045840,0.000000,0.003543,0.016165
00a55d1ba6f63109c208dbd80570520d5d80f563,0.000000,0.000811,0.019554,0.002393,1.000000,0.000000,0.012026,0.000324,0.009717,0.000693,...,0.001325,0.000000,0.015330,0.002074,0.002909,0.000000,0.001012,0.000626,0.000000,0.006487

In [12]:
target_user = user_item_matrix.index[0] # select the first user as the target user

similar_users = (
    similarity_df[target_user]
    .drop(target_user)  #exclude target user itself.
    .sort_values(ascending=False)
    .head(5)     #top 5 user chosen
)

similar_users

user_id
d10c36992a4bca783e0b7d253596ac1aa64e3260    0.156377
db6a78c78c9239aba33861dae7611a6893fb27d5    0.117535
c2d78d260f5bddc3fa2db228bb72ccae6ff7a8e1    0.117000
80e71630ebda6b635a246da2805ba9ae9c4367f5    0.108105
002b63a7e2247de6d62bc62f253474edc7dd044c    0.105672
Name: 001889ee41b5f31c404a1abe4af07b2377fa776b, dtype: float64

In [13]:
top_k_users = user_item_matrix.loc[similar_users.index] # get the listening history of the top 5 similar users

In [14]:
song_scores = top_k_users.sum(axis=0)  # sum the playcounts of each track across the top 5 similar users
song_scores

track_id
TRAAAED128E0783FAB    0.0
TRAABJS128F9325C99    0.0
TRAACKM12903CE5BE9    0.0
TRAACPH12903CF5F14    0.0
TRAACZN128F93236B1    0.0
                     ...
TRZZXVN128F93285B4    0.0
TRZZYMU128E0792400    1.0
TRZZZCN128F9317A03    0.0
TRZZZHL128F9329CFB    0.0
TRZZZRJ128F42819AF    0.0
Length: 17358, dtype: float64

In [15]:
# identify tracks that the target user has not listened to

target_history = user_item_matrix.loc[target_user]
unseen_songs = target_history[target_history == 0].index

In [16]:
#keep unseen songs

recommend_tracks = (
    song_scores[song_scores.index.isin(unseen_songs)]
    .sort_values(ascending=False)
    .head(10)  #top 10 recommendations based on Top 5 similar users
)

recommend_tracks

track_id
TRONYHY128F92C9D11    39.0
TRNNGMK128F423F034    31.0
TRDNHAW128F429DB9A    22.0
TRABOVH128F427D3B4    21.0
TRGCHLH12903CB7352    20.0
TRVQTQG128F93073B0    20.0
TRWZFIC128F933BCA3    19.0
TRAGSGF128E0780CA7    19.0
TRBOWSQ128F145E0F8    19.0
TREHENJ128E07953C7    17.0
dtype: float64

In [17]:
recommendation_result = (
    merged_df[
        merged_df["track_id"].isin(recommend_tracks.index)
    ][["track_id", "name", "artist", "genre"]]
    .drop_duplicates(subset="track_id")
    .set_index("track_id")
    .loc[recommend_tracks.index]
    .reset_index()
)

recommendation_result

,track_id,name,artist,genre
0,TRONYHY128F92C9D11,Revelry,Kings of Leon,Rock
1,TRNNGMK128F423F034,Where Is My Mind?,Pixies,Rock
2,TRDNHAW128F429DB9A,The Ballad of Michael Valentine,The Killers,Rock
3,TRABOVH128F427D3B4,Fancy Footwork,Chromeo,Electronic
4,TRGCHLH12903CB7352,Party In The U.S.A.,The Barden Bellas,Pop
5,TRVQTQG128F93073B0,Molly's Chambers,Kings of Leon,NaN
6,TRWZFIC128F933BCA3,In Person,The Pussycat Dolls,Pop
7,TRAGSGF128E0780CA7,One I Love,Coldplay,Rock
8,TRBOWSQ128F145E0F8,Why Don't You Find Out for Yourself,Morrissey,Rock
9,TREHENJ128E07953C7,Don't Cha,The Pussycat Dolls,NaN

In [18]:
# create training and testing data for hold-out evaluation

train_matrix = user_item_matrix.copy()
test_items = {}

In [28]:
# hide two previously listened tracks from each user for testing

import numpy as np

np.random.seed(42)

for user in train_matrix.index:
    listened_tracks = train_matrix.columns[
        train_matrix.loc[user] > 0
    ]

    if len(listened_tracks) > 2:
        hidden_tracks = np.random.choice(
            listened_tracks,
            size=2,
            replace=False
        )

        test_items[user] = set(hidden_tracks)

        train_matrix.loc[user, hidden_tracks] = 0

In [29]:
train_similarity = cosine_similarity(train_matrix)

train_similarity_df = pd.DataFrame(
    train_similarity,
    index=train_matrix.index,
    columns=train_matrix.index
)

In [30]:
def recommend_for_user(user, top_k=5, top_n=10):

    similar_users = (
        train_similarity_df[user]
        .drop(user)
        .sort_values(ascending=False)
        .head(top_k)
    )

    top_k_users = train_matrix.loc[similar_users.index]

    # weight each similar user's playcounts by their similarity score
    # weighted_scores = top_k_users.mul(
    #    similar_users,
    #    axis=0
    #)

    # combine the weighted scores for every track
    # song_scores = weighted_scores.sum(axis=0)

    song_scores = top_k_users.sum(axis=0)

    unseen_songs = train_matrix.columns[
        train_matrix.loc[user] == 0
    ]

    recommendations = (
        song_scores[
            song_scores.index.isin(unseen_songs) &
            (song_scores > 0)
        ]
        .sort_values(ascending=False)
        .head(top_n)
    )

    return recommendations.index.tolist()  # return the top 10 recommended track IDs

In [31]:
# prepare test users
test_users = list(test_items.keys())

np.random.seed(42)

if len(test_users) > 300:
    test_users = np.random.choice(
        test_users,
        size=300,
        replace=False
    )

# test ONE user
test_user = test_users[0]

actual_tracks = test_items[test_user]
recommended_tracks = recommend_for_user(test_user)

print("Actual hidden tracks:")
print(actual_tracks)

print("\nRecommended tracks:")
print(recommended_tracks)

print("\nHits:")
print(actual_tracks & set(recommended_tracks))

Actual hidden tracks:
{'TRAANSZ128F425DD63', 'TRUMDRI128F424FEFC'}

Recommended tracks:
['TRXJUGX128F42629F8', 'TRBFCSM128F42629F1', 'TRKOCXI128F9316B54', 'TRWAEUG12903CEB0A0', 'TRXPJQB128EF33FB4D', 'TREMWWD128F92FFBDC', 'TRXVLCB128F42629ED', 'TRUMDRI128F424FEFC', 'TRKGAYQ128F42827ED', 'TREJAMS128F14A950B']

Hits:
{'TRUMDRI128F424FEFC'}

In [32]:
precision_scores = []
recall_scores = []

total_hits = 0

for user in test_users:
    relevant_tracks = test_items[user]

    recommended_tracks = set(
        recommend_for_user(
            user,
            top_k=5,
            top_n=10
        )
    )

    hits = len(relevant_tracks & recommended_tracks)

    total_hits += hits
    precision_scores.append(hits / 10)
    recall_scores.append(hits / len(relevant_tracks))

print("Total Hits:", total_hits)
print("Total Test Users:", len(test_users))

Total Hits: 36
Total Test Users: 300

In [33]:
precision_at_10 = np.mean(precision_scores)
recall_at_10 = np.mean(recall_scores)

f1_at_10 = (
    2 * precision_at_10 * recall_at_10
    / (precision_at_10 + recall_at_10)
    if (precision_at_10 + recall_at_10) > 0
    else 0
)

print("Precision@10:", precision_at_10)
print("Recall@10   :", recall_at_10)
print("F1@10       :", f1_at_10)
print("Users evaluated:", len(test_users))

Precision@10: 0.012000000000000002
Recall@10   : 0.06
F1@10       : 0.020000000000000004
Users evaluated: 300